
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 25 21:31:22 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PARAPERTURA = 43;
  public static final int DOSPUNTOS = 51;
  public static final int FUNCTION = 6;
  public static final int MULT = 30;
  public static final int CASE = 17;
  public static final int INTEGER = 22;
  public static final int CONTINUE = 19;
  public static final int PUNTOCOMA = 50;
  public static final int ASTERISCO = 53;
  public static final int FOR = 15;
  public static final int NOIGUAL = 39;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int IGUAL = 37;
  public static final int PARCIERRE = 44;
  public static final int OR = 41;
  public static final int DIV = 31;
  public static final int NUM = 2;
  public static final int TYPEDEF = 4;
  public static final int MAIN = 10;
  public static final int IF = 12;
  public static final int AMPERSAND = 54;
  public static final int LLAVECIERRE = 46;
  public static final int EOF = 0;
  public static final int BOOLEAN = 21;
  public static final int LLAVEAPERTURA = 45;
  public static final int MAYOROIGUAL = 36;
  public static final int RETURN = 7;
  public static final int TRUE = 25;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int NULL = 27;
  public static final int MENOR = 34;
  public static final int CORCHAPERTURA = 47;
  public static final int MOD = 32;
  public static final int BREAK = 18;
  public static final int VOID = 8;
  public static final int MENOROIGUAL = 35;
  public static final int SWITCH = 16;
  public static final int PUNT = 24;
  public static final int MAYOR = 33;
  public static final int BARRABAJA = 55;
  public static final int ELSE = 13;
  public static final int PUNTO = 52;
  public static final int IGUALIGUAL = 38;
  public static final int IDEN = 3;
  public static final int WHILE = 14;
  public static final int DOLLAR = 56;
  public static final int LIST = 23;
  public static final int DEFAULT = 20;
  public static final int SUM = 28;
  public static final int FALSE = 26;
  public static final int STRUCT = 5;
  public static final int CORCHCIERRE = 48;
  public static final int SUB = 29;
  public static final int PRINT = 11;
}

