
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 23 14:04:00 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PARAPERTURA = 42;
  public static final int DOSPUNTOS = 50;
  public static final int FUNCTION = 6;
  public static final int MULT = 29;
  public static final int CASE = 16;
  public static final int INTEGER = 21;
  public static final int CONTINUE = 18;
  public static final int PUNTOCOMA = 49;
  public static final int ASTERISCO = 52;
  public static final int FOR = 14;
  public static final int NOIGUAL = 38;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int IGUAL = 36;
  public static final int PARCIERRE = 43;
  public static final int OR = 40;
  public static final int DIV = 30;
  public static final int NUM = 2;
  public static final int TYPEDEF = 4;
  public static final int MAIN = 10;
  public static final int IF = 11;
  public static final int AMPERSAND = 53;
  public static final int LLAVECIERRE = 45;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int LLAVEAPERTURA = 44;
  public static final int MAYOROIGUAL = 35;
  public static final int RETURN = 7;
  public static final int TRUE = 24;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int COMA = 48;
  public static final int NULL = 26;
  public static final int MENOR = 33;
  public static final int CORCHAPERTURA = 46;
  public static final int MOD = 31;
  public static final int BREAK = 17;
  public static final int VOID = 8;
  public static final int SWITCH = 15;
  public static final int MENOROIGUAL = 34;
  public static final int PUNT = 23;
  public static final int MAYOR = 32;
  public static final int BARRABAJA = 54;
  public static final int ELSE = 12;
  public static final int PUNTO = 51;
  public static final int IGUALIGUAL = 37;
  public static final int IDEN = 3;
  public static final int WHILE = 13;
  public static final int DOLLAR = 55;
  public static final int LIST = 22;
  public static final int DEFAULT = 19;
  public static final int SUM = 27;
  public static final int FALSE = 25;
  public static final int STRUCT = 5;
  public static final int CORCHCIERRE = 47;
  public static final int SUB = 28;
}

